const endpoints = {
  auth: {
    code: '/_/code',
    verify: '/_/verify',
    identity: '/_/identity',
    logout: '/_/logout',
  },
  user: {
    account: '-/user/account/data',
    accountIdentity: '-/user/account/identity',
    accountSessions: '-/user/account/sessions',
    accountSessionRevoke: '-/user/account/session/revoke',
    // Login methods
    accountMethods: '-/user/account/methods',
    accountMethodsSet: '-/user/account/methods/set',
    // Passkeys
    accountPasskeys: '-/user/account/passkeys',
    accountPasskeyRegisterBegin: '-/user/account/passkey/register/begin',
    accountPasskeyRegisterFinish: '-/user/account/passkey/register/finish',
    accountPasskeyRename: '-/user/account/passkey/rename',
    accountPasskeyDelete: '-/user/account/passkey/delete',
    // TOTP
    accountTotp: '-/user/account/totp',
    accountTotpSetup: '-/user/account/totp/setup',
    accountTotpVerify: '-/user/account/totp/verify',
    accountTotpDisable: '-/user/account/totp/disable',
    // Recovery
    accountRecovery: '-/user/account/recovery',
    accountRecoveryGenerate: '-/user/account/recovery/generate',
    // OAuth identities
    accountOauth: '-/user/account/oauth',
    accountOauthUnlink: '-/user/account/oauth/unlink',
    // Auth methods available on the server (public) - for OAuth begin flow
    authMethods: '/_/auth/methods',
    authOauthBegin: (provider: string) => `/_/auth/oauth/${provider}/begin`,
    // API Tokens
    accountTokens: '-/user/account/tokens',
    accountTokenCreate: '-/user/account/token/create',
    accountTokenDelete: '-/user/account/token/delete',
    // Preferences
    preferences: '-/user/preferences/data',
    preferencesSet: '-/user/preferences/set',
    preferencesReset: '-/user/preferences/reset',
    // Interests
    interests: '-/user/interests',
    interestsSet: '-/user/interests/set',
    interestsRemove: '-/user/interests/remove',
    interestsSearch: '-/user/interests/search',
    interestsSummary: '-/user/interests/summary',
  },
  system: {
    settings: '-/system/settings/list',
    settingsGet: '-/system/settings/get',
    settingsSet: '-/system/settings/set',
    users: '-/system/users/data',
    usersList: '-/system/users/list',
    usersGet: '-/system/users/get',
    usersCreate: '-/system/users/create',
    usersUpdate: '-/system/users/update',
    usersDelete: '-/system/users/delete',
    usersSuspend: '-/system/users/suspend',
    usersActivate: '-/system/users/activate',
    usersSessions: '-/system/users/sessions',
    usersSessionsRevoke: '-/system/users/sessions/revoke',
  },
  notifications: {
    categories: '-/notifications/categories',
    categoriesCreate: '-/notifications/categories/create',
    categoriesUpdate: '-/notifications/categories/update',
    categoriesDelete: '-/notifications/categories/delete',
    categoriesTest: '-/notifications/categories/test',
    subscriptions: '-/notifications/subscriptions',
    subscriptionsSetCategory: '-/notifications/subscriptions/set_category',
    subscriptionsReset: '-/notifications/subscriptions/reset',
    subscriptionsDelete: '-/notifications/subscriptions/delete',
    destinations: '-/notifications/destinations',
  },
  domains: {
    data: '-/domains/data',
    create: '-/domains/create',
    get: '-/domains/get',
    update: '-/domains/update',
    delete: '-/domains/delete',
    verify: '-/domains/verify',
    routeCreate: '-/domains/route/create',
    routeUpdate: '-/domains/route/update',
    routeDelete: '-/domains/route/delete',
    delegationCreate: '-/domains/delegation/create',
    delegationDelete: '-/domains/delegation/delete',
    userSearch: '-/domains/user/search',
    apps: '-/domains/apps',
    entities: '-/domains/entities',
  },
} as const

export default endpoints