/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDocumentPrivacyRouteImport } from './routes/_authenticated/document/privacy'
import { Route as AuthenticatedDocumentRulesRouteImport } from './routes/_authenticated/document/rules'
import { Route as AuthenticatedDocumentTermsRouteImport } from './routes/_authenticated/document/terms'
import { Route as AuthenticatedSystemDocumentsRouteImport } from './routes/_authenticated/system/documents'
import { Route as AuthenticatedSystemSettingsRouteImport } from './routes/_authenticated/system/settings'
import { Route as AuthenticatedSystemStatusRouteImport } from './routes/_authenticated/system/status'
import { Route as AuthenticatedSystemUsersRouteImport } from './routes/_authenticated/system/users'
import { Route as AuthenticatedUserAccountRouteImport } from './routes/_authenticated/user/account'
import { Route as AuthenticatedUserAccountsRouteImport } from './routes/_authenticated/user/accounts'
import { Route as AuthenticatedUserDisplayRouteImport } from './routes/_authenticated/user/display'
import { Route as AuthenticatedUserInterestsRouteImport } from './routes/_authenticated/user/interests'
import { Route as AuthenticatedUserLoginRouteImport } from './routes/_authenticated/user/login'
import { Route as AuthenticatedUserNotificationsRouteImport } from './routes/_authenticated/user/notifications'
import { Route as AuthenticatedUserPreferencesRouteImport } from './routes/_authenticated/user/preferences'
import { Route as AuthenticatedUserSessionsRouteImport } from './routes/_authenticated/user/sessions'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentPrivacyRoute =
  AuthenticatedDocumentPrivacyRouteImport.update({
    id: '/document/privacy',
    path: '/document/privacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentRulesRoute =
  AuthenticatedDocumentRulesRouteImport.update({
    id: '/document/rules',
    path: '/document/rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentTermsRoute =
  AuthenticatedDocumentTermsRouteImport.update({
    id: '/document/terms',
    path: '/document/terms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDocumentsRoute =
  AuthenticatedSystemDocumentsRouteImport.update({
    id: '/system/documents',
    path: '/system/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSettingsRoute =
  AuthenticatedSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemStatusRoute =
  AuthenticatedSystemStatusRouteImport.update({
    id: '/system/status',
    path: '/system/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersRoute =
  AuthenticatedSystemUsersRouteImport.update({
    id: '/system/users',
    path: '/system/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserAccountRoute =
  AuthenticatedUserAccountRouteImport.update({
    id: '/user/account',
    path: '/user/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserAccountsRoute =
  AuthenticatedUserAccountsRouteImport.update({
    id: '/user/accounts',
    path: '/user/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserDisplayRoute =
  AuthenticatedUserDisplayRouteImport.update({
    id: '/user/display',
    path: '/user/display',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserInterestsRoute =
  AuthenticatedUserInterestsRouteImport.update({
    id: '/user/interests',
    path: '/user/interests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserLoginRoute = AuthenticatedUserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserNotificationsRoute =
  AuthenticatedUserNotificationsRouteImport.update({
    id: '/user/notifications',
    path: '/user/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserPreferencesRoute =
  AuthenticatedUserPreferencesRouteImport.update({
    id: '/user/preferences',
    path: '/user/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserSessionsRoute =
  AuthenticatedUserSessionsRouteImport.update({
    id: '/user/sessions',
    path: '/user/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/document/terms': typeof AuthenticatedDocumentTermsRoute
  '/system/documents': typeof AuthenticatedSystemDocumentsRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/status': typeof AuthenticatedSystemStatusRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/user/account': typeof AuthenticatedUserAccountRoute
  '/user/accounts': typeof AuthenticatedUserAccountsRoute
  '/user/display': typeof AuthenticatedUserDisplayRoute
  '/user/interests': typeof AuthenticatedUserInterestsRoute
  '/user/login': typeof AuthenticatedUserLoginRoute
  '/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/user/preferences': typeof AuthenticatedUserPreferencesRoute
  '/user/sessions': typeof AuthenticatedUserSessionsRoute
}
export interface FileRoutesByTo {
  '/domains': typeof AuthenticatedDomainsRoute
  '/': typeof AuthenticatedIndexRoute
  '/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/document/terms': typeof AuthenticatedDocumentTermsRoute
  '/system/documents': typeof AuthenticatedSystemDocumentsRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/status': typeof AuthenticatedSystemStatusRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/user/account': typeof AuthenticatedUserAccountRoute
  '/user/accounts': typeof AuthenticatedUserAccountsRoute
  '/user/display': typeof AuthenticatedUserDisplayRoute
  '/user/interests': typeof AuthenticatedUserInterestsRoute
  '/user/login': typeof AuthenticatedUserLoginRoute
  '/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/user/preferences': typeof AuthenticatedUserPreferencesRoute
  '/user/sessions': typeof AuthenticatedUserSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/_authenticated/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/_authenticated/document/terms': typeof AuthenticatedDocumentTermsRoute
  '/_authenticated/system/documents': typeof AuthenticatedSystemDocumentsRoute
  '/_authenticated/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/_authenticated/system/status': typeof AuthenticatedSystemStatusRoute
  '/_authenticated/system/users': typeof AuthenticatedSystemUsersRoute
  '/_authenticated/user/account': typeof AuthenticatedUserAccountRoute
  '/_authenticated/user/accounts': typeof AuthenticatedUserAccountsRoute
  '/_authenticated/user/display': typeof AuthenticatedUserDisplayRoute
  '/_authenticated/user/interests': typeof AuthenticatedUserInterestsRoute
  '/_authenticated/user/login': typeof AuthenticatedUserLoginRoute
  '/_authenticated/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/_authenticated/user/preferences': typeof AuthenticatedUserPreferencesRoute
  '/_authenticated/user/sessions': typeof AuthenticatedUserSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domains'
    | '/document/privacy'
    | '/document/rules'
    | '/document/terms'
    | '/system/documents'
    | '/system/settings'
    | '/system/status'
    | '/system/users'
    | '/user/account'
    | '/user/accounts'
    | '/user/display'
    | '/user/interests'
    | '/user/login'
    | '/user/notifications'
    | '/user/preferences'
    | '/user/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/domains'
    | '/'
    | '/document/privacy'
    | '/document/rules'
    | '/document/terms'
    | '/system/documents'
    | '/system/settings'
    | '/system/status'
    | '/system/users'
    | '/user/account'
    | '/user/accounts'
    | '/user/display'
    | '/user/interests'
    | '/user/login'
    | '/user/notifications'
    | '/user/preferences'
    | '/user/sessions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/domains'
    | '/_authenticated/'
    | '/_authenticated/document/privacy'
    | '/_authenticated/document/rules'
    | '/_authenticated/document/terms'
    | '/_authenticated/system/documents'
    | '/_authenticated/system/settings'
    | '/_authenticated/system/status'
    | '/_authenticated/system/users'
    | '/_authenticated/user/account'
    | '/_authenticated/user/accounts'
    | '/_authenticated/user/display'
    | '/_authenticated/user/interests'
    | '/_authenticated/user/login'
    | '/_authenticated/user/notifications'
    | '/_authenticated/user/preferences'
    | '/_authenticated/user/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/privacy': {
      id: '/_authenticated/document/privacy'
      path: '/document/privacy'
      fullPath: '/document/privacy'
      preLoaderRoute: typeof AuthenticatedDocumentPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/rules': {
      id: '/_authenticated/document/rules'
      path: '/document/rules'
      fullPath: '/document/rules'
      preLoaderRoute: typeof AuthenticatedDocumentRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/terms': {
      id: '/_authenticated/document/terms'
      path: '/document/terms'
      fullPath: '/document/terms'
      preLoaderRoute: typeof AuthenticatedDocumentTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/documents': {
      id: '/_authenticated/system/documents'
      path: '/system/documents'
      fullPath: '/system/documents'
      preLoaderRoute: typeof AuthenticatedSystemDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/settings': {
      id: '/_authenticated/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/status': {
      id: '/_authenticated/system/status'
      path: '/system/status'
      fullPath: '/system/status'
      preLoaderRoute: typeof AuthenticatedSystemStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users': {
      id: '/_authenticated/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AuthenticatedSystemUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/account': {
      id: '/_authenticated/user/account'
      path: '/user/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof AuthenticatedUserAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/accounts': {
      id: '/_authenticated/user/accounts'
      path: '/user/accounts'
      fullPath: '/user/accounts'
      preLoaderRoute: typeof AuthenticatedUserAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/display': {
      id: '/_authenticated/user/display'
      path: '/user/display'
      fullPath: '/user/display'
      preLoaderRoute: typeof AuthenticatedUserDisplayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/interests': {
      id: '/_authenticated/user/interests'
      path: '/user/interests'
      fullPath: '/user/interests'
      preLoaderRoute: typeof AuthenticatedUserInterestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/login': {
      id: '/_authenticated/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof AuthenticatedUserLoginRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/notifications': {
      id: '/_authenticated/user/notifications'
      path: '/user/notifications'
      fullPath: '/user/notifications'
      preLoaderRoute: typeof AuthenticatedUserNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/preferences': {
      id: '/_authenticated/user/preferences'
      path: '/user/preferences'
      fullPath: '/user/preferences'
      preLoaderRoute: typeof AuthenticatedUserPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/sessions': {
      id: '/_authenticated/user/sessions'
      path: '/user/sessions'
      fullPath: '/user/sessions'
      preLoaderRoute: typeof AuthenticatedUserSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentPrivacyRoute: typeof AuthenticatedDocumentPrivacyRoute
  AuthenticatedDocumentRulesRoute: typeof AuthenticatedDocumentRulesRoute
  AuthenticatedDocumentTermsRoute: typeof AuthenticatedDocumentTermsRoute
  AuthenticatedSystemDocumentsRoute: typeof AuthenticatedSystemDocumentsRoute
  AuthenticatedSystemSettingsRoute: typeof AuthenticatedSystemSettingsRoute
  AuthenticatedSystemStatusRoute: typeof AuthenticatedSystemStatusRoute
  AuthenticatedSystemUsersRoute: typeof AuthenticatedSystemUsersRoute
  AuthenticatedUserAccountRoute: typeof AuthenticatedUserAccountRoute
  AuthenticatedUserAccountsRoute: typeof AuthenticatedUserAccountsRoute
  AuthenticatedUserDisplayRoute: typeof AuthenticatedUserDisplayRoute
  AuthenticatedUserInterestsRoute: typeof AuthenticatedUserInterestsRoute
  AuthenticatedUserLoginRoute: typeof AuthenticatedUserLoginRoute
  AuthenticatedUserNotificationsRoute: typeof AuthenticatedUserNotificationsRoute
  AuthenticatedUserPreferencesRoute: typeof AuthenticatedUserPreferencesRoute
  AuthenticatedUserSessionsRoute: typeof AuthenticatedUserSessionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentPrivacyRoute: AuthenticatedDocumentPrivacyRoute,
  AuthenticatedDocumentRulesRoute: AuthenticatedDocumentRulesRoute,
  AuthenticatedDocumentTermsRoute: AuthenticatedDocumentTermsRoute,
  AuthenticatedSystemDocumentsRoute: AuthenticatedSystemDocumentsRoute,
  AuthenticatedSystemSettingsRoute: AuthenticatedSystemSettingsRoute,
  AuthenticatedSystemStatusRoute: AuthenticatedSystemStatusRoute,
  AuthenticatedSystemUsersRoute: AuthenticatedSystemUsersRoute,
  AuthenticatedUserAccountRoute: AuthenticatedUserAccountRoute,
  AuthenticatedUserAccountsRoute: AuthenticatedUserAccountsRoute,
  AuthenticatedUserDisplayRoute: AuthenticatedUserDisplayRoute,
  AuthenticatedUserInterestsRoute: AuthenticatedUserInterestsRoute,
  AuthenticatedUserLoginRoute: AuthenticatedUserLoginRoute,
  AuthenticatedUserNotificationsRoute: AuthenticatedUserNotificationsRoute,
  AuthenticatedUserPreferencesRoute: AuthenticatedUserPreferencesRoute,
  AuthenticatedUserSessionsRoute: AuthenticatedUserSessionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
