/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AuthenticatedUserTokensRouteImport } from './routes/_authenticated/user/tokens'
import { Route as AuthenticatedUserSessionsRouteImport } from './routes/_authenticated/user/sessions'
import { Route as AuthenticatedUserReplicationRouteImport } from './routes/_authenticated/user/replication'
import { Route as AuthenticatedUserPreferencesRouteImport } from './routes/_authenticated/user/preferences'
import { Route as AuthenticatedUserNotificationsRouteImport } from './routes/_authenticated/user/notifications'
import { Route as AuthenticatedUserLoginRouteImport } from './routes/_authenticated/user/login'
import { Route as AuthenticatedUserInterestsRouteImport } from './routes/_authenticated/user/interests'
import { Route as AuthenticatedUserDisplayRouteImport } from './routes/_authenticated/user/display'
import { Route as AuthenticatedUserAccountsRouteImport } from './routes/_authenticated/user/accounts'
import { Route as AuthenticatedUserAccountRouteImport } from './routes/_authenticated/user/account'
import { Route as AuthenticatedSystemUsersRouteImport } from './routes/_authenticated/system/users'
import { Route as AuthenticatedSystemStatusRouteImport } from './routes/_authenticated/system/status'
import { Route as AuthenticatedSystemSettingsRouteImport } from './routes/_authenticated/system/settings'
import { Route as AuthenticatedSystemReplicationRouteImport } from './routes/_authenticated/system/replication'
import { Route as AuthenticatedSystemDocumentsRouteImport } from './routes/_authenticated/system/documents'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDocumentTermsRouteImport } from './routes/_authenticated/document/terms'
import { Route as AuthenticatedDocumentRulesRouteImport } from './routes/_authenticated/document/rules'
import { Route as AuthenticatedDocumentPrivacyRouteImport } from './routes/_authenticated/document/privacy'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserTokensRoute = AuthenticatedUserTokensRouteImport.update({
  id: '/user/tokens',
  path: '/user/tokens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserSessionsRoute =
  AuthenticatedUserSessionsRouteImport.update({
    id: '/user/sessions',
    path: '/user/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserReplicationRoute =
  AuthenticatedUserReplicationRouteImport.update({
    id: '/user/replication',
    path: '/user/replication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserPreferencesRoute =
  AuthenticatedUserPreferencesRouteImport.update({
    id: '/user/preferences',
    path: '/user/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserNotificationsRoute =
  AuthenticatedUserNotificationsRouteImport.update({
    id: '/user/notifications',
    path: '/user/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserLoginRoute = AuthenticatedUserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserInterestsRoute =
  AuthenticatedUserInterestsRouteImport.update({
    id: '/user/interests',
    path: '/user/interests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserDisplayRoute =
  AuthenticatedUserDisplayRouteImport.update({
    id: '/user/display',
    path: '/user/display',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserAccountsRoute =
  AuthenticatedUserAccountsRouteImport.update({
    id: '/user/accounts',
    path: '/user/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserAccountRoute =
  AuthenticatedUserAccountRouteImport.update({
    id: '/user/account',
    path: '/user/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersRoute =
  AuthenticatedSystemUsersRouteImport.update({
    id: '/system/users',
    path: '/system/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemStatusRoute =
  AuthenticatedSystemStatusRouteImport.update({
    id: '/system/status',
    path: '/system/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSettingsRoute =
  AuthenticatedSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemReplicationRoute =
  AuthenticatedSystemReplicationRouteImport.update({
    id: '/system/replication',
    path: '/system/replication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDocumentsRoute =
  AuthenticatedSystemDocumentsRouteImport.update({
    id: '/system/documents',
    path: '/system/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentTermsRoute =
  AuthenticatedDocumentTermsRouteImport.update({
    id: '/document/terms',
    path: '/document/terms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentRulesRoute =
  AuthenticatedDocumentRulesRouteImport.update({
    id: '/document/rules',
    path: '/document/rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentPrivacyRoute =
  AuthenticatedDocumentPrivacyRouteImport.update({
    id: '/document/privacy',
    path: '/document/privacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/domains': typeof AuthenticatedDomainsRoute
  '/': typeof AuthenticatedIndexRoute
  '/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/document/terms': typeof AuthenticatedDocumentTermsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/system/documents': typeof AuthenticatedSystemDocumentsRoute
  '/system/replication': typeof AuthenticatedSystemReplicationRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/status': typeof AuthenticatedSystemStatusRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/user/account': typeof AuthenticatedUserAccountRoute
  '/user/accounts': typeof AuthenticatedUserAccountsRoute
  '/user/display': typeof AuthenticatedUserDisplayRoute
  '/user/interests': typeof AuthenticatedUserInterestsRoute
  '/user/login': typeof AuthenticatedUserLoginRoute
  '/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/user/preferences': typeof AuthenticatedUserPreferencesRoute
  '/user/replication': typeof AuthenticatedUserReplicationRoute
  '/user/sessions': typeof AuthenticatedUserSessionsRoute
  '/user/tokens': typeof AuthenticatedUserTokensRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/domains': typeof AuthenticatedDomainsRoute
  '/': typeof AuthenticatedIndexRoute
  '/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/document/terms': typeof AuthenticatedDocumentTermsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/system/documents': typeof AuthenticatedSystemDocumentsRoute
  '/system/replication': typeof AuthenticatedSystemReplicationRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/status': typeof AuthenticatedSystemStatusRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/user/account': typeof AuthenticatedUserAccountRoute
  '/user/accounts': typeof AuthenticatedUserAccountsRoute
  '/user/display': typeof AuthenticatedUserDisplayRoute
  '/user/interests': typeof AuthenticatedUserInterestsRoute
  '/user/login': typeof AuthenticatedUserLoginRoute
  '/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/user/preferences': typeof AuthenticatedUserPreferencesRoute
  '/user/replication': typeof AuthenticatedUserReplicationRoute
  '/user/sessions': typeof AuthenticatedUserSessionsRoute
  '/user/tokens': typeof AuthenticatedUserTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/document/privacy': typeof AuthenticatedDocumentPrivacyRoute
  '/_authenticated/document/rules': typeof AuthenticatedDocumentRulesRoute
  '/_authenticated/document/terms': typeof AuthenticatedDocumentTermsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/system/documents': typeof AuthenticatedSystemDocumentsRoute
  '/_authenticated/system/replication': typeof AuthenticatedSystemReplicationRoute
  '/_authenticated/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/_authenticated/system/status': typeof AuthenticatedSystemStatusRoute
  '/_authenticated/system/users': typeof AuthenticatedSystemUsersRoute
  '/_authenticated/user/account': typeof AuthenticatedUserAccountRoute
  '/_authenticated/user/accounts': typeof AuthenticatedUserAccountsRoute
  '/_authenticated/user/display': typeof AuthenticatedUserDisplayRoute
  '/_authenticated/user/interests': typeof AuthenticatedUserInterestsRoute
  '/_authenticated/user/login': typeof AuthenticatedUserLoginRoute
  '/_authenticated/user/notifications': typeof AuthenticatedUserNotificationsRoute
  '/_authenticated/user/preferences': typeof AuthenticatedUserPreferencesRoute
  '/_authenticated/user/replication': typeof AuthenticatedUserReplicationRoute
  '/_authenticated/user/sessions': typeof AuthenticatedUserSessionsRoute
  '/_authenticated/user/tokens': typeof AuthenticatedUserTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/domains'
    | '/'
    | '/document/privacy'
    | '/document/rules'
    | '/document/terms'
    | '/errors/$error'
    | '/system/documents'
    | '/system/replication'
    | '/system/settings'
    | '/system/status'
    | '/system/users'
    | '/user/account'
    | '/user/accounts'
    | '/user/display'
    | '/user/interests'
    | '/user/login'
    | '/user/notifications'
    | '/user/preferences'
    | '/user/replication'
    | '/user/sessions'
    | '/user/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/domains'
    | '/'
    | '/document/privacy'
    | '/document/rules'
    | '/document/terms'
    | '/errors/$error'
    | '/system/documents'
    | '/system/replication'
    | '/system/settings'
    | '/system/status'
    | '/system/users'
    | '/user/account'
    | '/user/accounts'
    | '/user/display'
    | '/user/interests'
    | '/user/login'
    | '/user/notifications'
    | '/user/preferences'
    | '/user/replication'
    | '/user/sessions'
    | '/user/tokens'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/domains'
    | '/_authenticated/'
    | '/_authenticated/document/privacy'
    | '/_authenticated/document/rules'
    | '/_authenticated/document/terms'
    | '/_authenticated/errors/$error'
    | '/_authenticated/system/documents'
    | '/_authenticated/system/replication'
    | '/_authenticated/system/settings'
    | '/_authenticated/system/status'
    | '/_authenticated/system/users'
    | '/_authenticated/user/account'
    | '/_authenticated/user/accounts'
    | '/_authenticated/user/display'
    | '/_authenticated/user/interests'
    | '/_authenticated/user/login'
    | '/_authenticated/user/notifications'
    | '/_authenticated/user/preferences'
    | '/_authenticated/user/replication'
    | '/_authenticated/user/sessions'
    | '/_authenticated/user/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user/tokens': {
      id: '/_authenticated/user/tokens'
      path: '/user/tokens'
      fullPath: '/user/tokens'
      preLoaderRoute: typeof AuthenticatedUserTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/sessions': {
      id: '/_authenticated/user/sessions'
      path: '/user/sessions'
      fullPath: '/user/sessions'
      preLoaderRoute: typeof AuthenticatedUserSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/replication': {
      id: '/_authenticated/user/replication'
      path: '/user/replication'
      fullPath: '/user/replication'
      preLoaderRoute: typeof AuthenticatedUserReplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/preferences': {
      id: '/_authenticated/user/preferences'
      path: '/user/preferences'
      fullPath: '/user/preferences'
      preLoaderRoute: typeof AuthenticatedUserPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/notifications': {
      id: '/_authenticated/user/notifications'
      path: '/user/notifications'
      fullPath: '/user/notifications'
      preLoaderRoute: typeof AuthenticatedUserNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/login': {
      id: '/_authenticated/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof AuthenticatedUserLoginRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/interests': {
      id: '/_authenticated/user/interests'
      path: '/user/interests'
      fullPath: '/user/interests'
      preLoaderRoute: typeof AuthenticatedUserInterestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/display': {
      id: '/_authenticated/user/display'
      path: '/user/display'
      fullPath: '/user/display'
      preLoaderRoute: typeof AuthenticatedUserDisplayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/accounts': {
      id: '/_authenticated/user/accounts'
      path: '/user/accounts'
      fullPath: '/user/accounts'
      preLoaderRoute: typeof AuthenticatedUserAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/account': {
      id: '/_authenticated/user/account'
      path: '/user/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof AuthenticatedUserAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users': {
      id: '/_authenticated/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AuthenticatedSystemUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/status': {
      id: '/_authenticated/system/status'
      path: '/system/status'
      fullPath: '/system/status'
      preLoaderRoute: typeof AuthenticatedSystemStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/settings': {
      id: '/_authenticated/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/replication': {
      id: '/_authenticated/system/replication'
      path: '/system/replication'
      fullPath: '/system/replication'
      preLoaderRoute: typeof AuthenticatedSystemReplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/documents': {
      id: '/_authenticated/system/documents'
      path: '/system/documents'
      fullPath: '/system/documents'
      preLoaderRoute: typeof AuthenticatedSystemDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/terms': {
      id: '/_authenticated/document/terms'
      path: '/document/terms'
      fullPath: '/document/terms'
      preLoaderRoute: typeof AuthenticatedDocumentTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/rules': {
      id: '/_authenticated/document/rules'
      path: '/document/rules'
      fullPath: '/document/rules'
      preLoaderRoute: typeof AuthenticatedDocumentRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document/privacy': {
      id: '/_authenticated/document/privacy'
      path: '/document/privacy'
      fullPath: '/document/privacy'
      preLoaderRoute: typeof AuthenticatedDocumentPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentPrivacyRoute: typeof AuthenticatedDocumentPrivacyRoute
  AuthenticatedDocumentRulesRoute: typeof AuthenticatedDocumentRulesRoute
  AuthenticatedDocumentTermsRoute: typeof AuthenticatedDocumentTermsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSystemDocumentsRoute: typeof AuthenticatedSystemDocumentsRoute
  AuthenticatedSystemReplicationRoute: typeof AuthenticatedSystemReplicationRoute
  AuthenticatedSystemSettingsRoute: typeof AuthenticatedSystemSettingsRoute
  AuthenticatedSystemStatusRoute: typeof AuthenticatedSystemStatusRoute
  AuthenticatedSystemUsersRoute: typeof AuthenticatedSystemUsersRoute
  AuthenticatedUserAccountRoute: typeof AuthenticatedUserAccountRoute
  AuthenticatedUserAccountsRoute: typeof AuthenticatedUserAccountsRoute
  AuthenticatedUserDisplayRoute: typeof AuthenticatedUserDisplayRoute
  AuthenticatedUserInterestsRoute: typeof AuthenticatedUserInterestsRoute
  AuthenticatedUserLoginRoute: typeof AuthenticatedUserLoginRoute
  AuthenticatedUserNotificationsRoute: typeof AuthenticatedUserNotificationsRoute
  AuthenticatedUserPreferencesRoute: typeof AuthenticatedUserPreferencesRoute
  AuthenticatedUserReplicationRoute: typeof AuthenticatedUserReplicationRoute
  AuthenticatedUserSessionsRoute: typeof AuthenticatedUserSessionsRoute
  AuthenticatedUserTokensRoute: typeof AuthenticatedUserTokensRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentPrivacyRoute: AuthenticatedDocumentPrivacyRoute,
  AuthenticatedDocumentRulesRoute: AuthenticatedDocumentRulesRoute,
  AuthenticatedDocumentTermsRoute: AuthenticatedDocumentTermsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSystemDocumentsRoute: AuthenticatedSystemDocumentsRoute,
  AuthenticatedSystemReplicationRoute: AuthenticatedSystemReplicationRoute,
  AuthenticatedSystemSettingsRoute: AuthenticatedSystemSettingsRoute,
  AuthenticatedSystemStatusRoute: AuthenticatedSystemStatusRoute,
  AuthenticatedSystemUsersRoute: AuthenticatedSystemUsersRoute,
  AuthenticatedUserAccountRoute: AuthenticatedUserAccountRoute,
  AuthenticatedUserAccountsRoute: AuthenticatedUserAccountsRoute,
  AuthenticatedUserDisplayRoute: AuthenticatedUserDisplayRoute,
  AuthenticatedUserInterestsRoute: AuthenticatedUserInterestsRoute,
  AuthenticatedUserLoginRoute: AuthenticatedUserLoginRoute,
  AuthenticatedUserNotificationsRoute: AuthenticatedUserNotificationsRoute,
  AuthenticatedUserPreferencesRoute: AuthenticatedUserPreferencesRoute,
  AuthenticatedUserReplicationRoute: AuthenticatedUserReplicationRoute,
  AuthenticatedUserSessionsRoute: AuthenticatedUserSessionsRoute,
  AuthenticatedUserTokensRoute: AuthenticatedUserTokensRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
