/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AuthenticatedUserPreferencesRouteImport } from './routes/_authenticated/user/preferences'
import { Route as AuthenticatedUserDomainsRouteImport } from './routes/_authenticated/user/domains'
import { Route as AuthenticatedUserAccountRouteImport } from './routes/_authenticated/user/account'
import { Route as AuthenticatedSystemUsersRouteImport } from './routes/_authenticated/system/users'
import { Route as AuthenticatedSystemSettingsRouteImport } from './routes/_authenticated/system/settings'
import { Route as AuthenticatedSystemDomainsRouteImport } from './routes/_authenticated/system/domains'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserPreferencesRoute =
  AuthenticatedUserPreferencesRouteImport.update({
    id: '/user/preferences',
    path: '/user/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserDomainsRoute =
  AuthenticatedUserDomainsRouteImport.update({
    id: '/user/domains',
    path: '/user/domains',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserAccountRoute =
  AuthenticatedUserAccountRouteImport.update({
    id: '/user/account',
    path: '/user/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersRoute =
  AuthenticatedSystemUsersRouteImport.update({
    id: '/system/users',
    path: '/system/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSettingsRoute =
  AuthenticatedSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDomainsRoute =
  AuthenticatedSystemDomainsRouteImport.update({
    id: '/system/domains',
    path: '/system/domains',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/system/domains': typeof AuthenticatedSystemDomainsRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/user/account': typeof AuthenticatedUserAccountRoute
  '/user/domains': typeof AuthenticatedUserDomainsRoute
  '/user/preferences': typeof AuthenticatedUserPreferencesRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/system/domains': typeof AuthenticatedSystemDomainsRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/user/account': typeof AuthenticatedUserAccountRoute
  '/user/domains': typeof AuthenticatedUserDomainsRoute
  '/user/preferences': typeof AuthenticatedUserPreferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/system/domains': typeof AuthenticatedSystemDomainsRoute
  '/_authenticated/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/_authenticated/system/users': typeof AuthenticatedSystemUsersRoute
  '/_authenticated/user/account': typeof AuthenticatedUserAccountRoute
  '/_authenticated/user/domains': typeof AuthenticatedUserDomainsRoute
  '/_authenticated/user/preferences': typeof AuthenticatedUserPreferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/system/domains'
    | '/system/settings'
    | '/system/users'
    | '/user/account'
    | '/user/domains'
    | '/user/preferences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/system/domains'
    | '/system/settings'
    | '/system/users'
    | '/user/account'
    | '/user/domains'
    | '/user/preferences'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/system/domains'
    | '/_authenticated/system/settings'
    | '/_authenticated/system/users'
    | '/_authenticated/user/account'
    | '/_authenticated/user/domains'
    | '/_authenticated/user/preferences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user/preferences': {
      id: '/_authenticated/user/preferences'
      path: '/user/preferences'
      fullPath: '/user/preferences'
      preLoaderRoute: typeof AuthenticatedUserPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/domains': {
      id: '/_authenticated/user/domains'
      path: '/user/domains'
      fullPath: '/user/domains'
      preLoaderRoute: typeof AuthenticatedUserDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/account': {
      id: '/_authenticated/user/account'
      path: '/user/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof AuthenticatedUserAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users': {
      id: '/_authenticated/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AuthenticatedSystemUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/settings': {
      id: '/_authenticated/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/domains': {
      id: '/_authenticated/system/domains'
      path: '/system/domains'
      fullPath: '/system/domains'
      preLoaderRoute: typeof AuthenticatedSystemDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSystemDomainsRoute: typeof AuthenticatedSystemDomainsRoute
  AuthenticatedSystemSettingsRoute: typeof AuthenticatedSystemSettingsRoute
  AuthenticatedSystemUsersRoute: typeof AuthenticatedSystemUsersRoute
  AuthenticatedUserAccountRoute: typeof AuthenticatedUserAccountRoute
  AuthenticatedUserDomainsRoute: typeof AuthenticatedUserDomainsRoute
  AuthenticatedUserPreferencesRoute: typeof AuthenticatedUserPreferencesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSystemDomainsRoute: AuthenticatedSystemDomainsRoute,
  AuthenticatedSystemSettingsRoute: AuthenticatedSystemSettingsRoute,
  AuthenticatedSystemUsersRoute: AuthenticatedSystemUsersRoute,
  AuthenticatedUserAccountRoute: AuthenticatedUserAccountRoute,
  AuthenticatedUserDomainsRoute: AuthenticatedUserDomainsRoute,
  AuthenticatedUserPreferencesRoute: AuthenticatedUserPreferencesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
